collections:
  - name: ansible.posix
  - name: community.general
roles:
  - name: snider.server_base
  - name: geerlingguy.ntp
  - name: geerlingguy.nginx
  - name: geerlingguy.postgresql
  - name: geerlingguy.nodejs
  - name: geerlingguy.supervisor
  - name: geerlingguy.swap
  - name: geerlingguy.pip
  - name: robertdebock.logrotate